<a href="https://colab.research.google.com/github/VincentLin95/data-science-bootcamp-8/blob/main/Python/HW03%20-%20API%20Requesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# import library
import requests
import time
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# API requesting
url = "http://universities.hipolabs.com/search?country=United+States"
name = []
domain = []
webpage = []

for i in range(500):
    resp = requests.get(url)
    if resp.status_code == 200:
        json_data = resp.json()
        name.append(json_data[i]["name"])
        domain.append(json_data[i]["domains"])
        webpage.append(json_data[i]["web_pages"])
    else:
        name.append(json_data["error"])
        domain.append(json_data["error"])
        webpage.append(json_data["error"])

time.sleep(1)

# create dataframe
USuniversitylist = pd.DataFrame(data= {
    "Name": name,
    "Domain": domain,
    "Webpage": webpage
})

USuniversitylist = USuniversitylist.style.hide_index()
USuniversitylist